export const lanes = [
 {
  id:'residential', path:'residential-solar', name:'Residential solar', short:'A home that works for you.', eyebrow:'For homeowners', headline:'A clearer energy plan.\nFor the place you call home.',
  intro:'Explore solar and storage around your home, your electricity use and the things you want to keep running. Start with a practical fit conversation before choosing equipment or financing.',
  audience:'Homeowners, authorized property representatives and people planning a home energy upgrade.',
  cards:[['Start with your home','Location, roof condition, shade and property authority shape the first review. An attractive roof is a starting point; it is not a production estimate.'],['Make room for real life','Your electric usage and future loads matter. An EV, home business or changing occupancy can influence what should be evaluated. An approximate range is enough to begin.'],['Decide what backup means','If storage interests you, identify essential loads and the duration you have in mind. Whole-home backup and automatic operation depend on the complete system design.']],
  detailTitle:'Know what belongs in the next conversation.',
  paragraphs:['The first step is to understand the property and check available installation and service coverage. If there appears to be a fit, the next stage can address roof suitability, electrical equipment, utility rules and your usage. We will explain what information is needed before you share detailed documents.','Solar production, utility-bill effects, financing terms and available programs all depend on your circumstances. A useful comparison identifies the system assumptions, current utility tariff, costs, ownership terms and responsibilities. Any savings or incentive discussion should be supported by current project-specific information.','You do not need to know the right system size. Choose “help me determine this” and describe the outcome you want. Keep utility account numbers, passwords, tax records and financial credentials out of the first inquiry.'],
  next:'Share your city or ZIP, your role in the property, your interest in solar or storage and your timing. Sol will first assess coverage and the appropriate next review.',
  faq:[['Do I need my electric bill now?','No. A rough usage range is optional. Detailed usage can be requested later through an appropriate sharing process.'],['Can solar keep my home running during an outage?','Solar alone does not establish backup capability. Storage, controls, electrical design and utility requirements must be assessed for the intended loads.'],['Will I receive a price or incentive approval from this form?','No. This is an inquiry. Firm pricing, financing and program eligibility need a separate verified review.']], related:['battery'],
  questions:[['authority','Your relationship to the home','select',['Owner','Authorized representative','Considering purchase','Help me determine this']],['need','What would you like to explore?','select',['Solar','Solar + storage','Help me determine this']],['usage','Approximate monthly electricity use (optional)','text',null,'For example, 1,200 kWh; unknown is fine']]
 },
 {
  id:'commercial', path:'commercial-solar', name:'Commercial solar', short:'Put your property in the picture.', eyebrow:'For owners & facility teams', headline:'Your property. Your operations.\nA more informed energy decision.',
  intro:'Explore rooftop, carport or ground-mounted solar with the people responsible for the site, the budget and daily operations. Begin with the use case and the constraints that matter.',
  audience:'Business owners, facility managers, property owners and authorized representatives evaluating one or more commercial sites.',
  cards:[['Property & authority','Clarify who controls the roof, parking or land, how long the business expects to use it and who can authorize a project.'],['Load & operating pattern','Business hours, interval usage and demand patterns can change a project’s value. Public opening hours are not a substitute for energy data.'],['Buildability & timing','Roof life, parking use, access, utility processes and business continuity need attention before a design or installation schedule is promised.']],
  detailTitle:'A useful commercial review connects operations and economics.',
  paragraphs:['Start with the facility type and the areas you want to consider. A warehouse roof, a busy parking lot and an open parcel each involve different constraints. The initial inquiry helps organize the right conversation with the property, operations and financial stakeholders.','A later technical and commercial review can compare likely production, utility treatment, demand patterns, equipment and proposed contract terms. Sol coordinates qualification and business development; licensed design, installation, financing and other delivery responsibilities are project-specific and must be established separately.','For a portfolio, begin with one representative site and note the number of additional locations. A successful review at one property does not automatically establish feasibility at another. Site-specific evidence keeps the expansion decision useful.'],
  next:'Tell us your facility type, city or ZIP, decision role, preferred installation area and timing. Optional usage and portfolio context help prepare a relevant follow-up.',
  faq:[['Can I explore solar for a leased facility?','Yes. Tell us your role and what is known about property permission. The owner’s authority and relevant lease terms must be addressed.'],['Can you assess more than one site?','Indicate the number of sites and start with a representative location. Each location needs its own coverage and feasibility review.'],['Are incentives included automatically?','No. Current program rules and project eligibility require separate verification. No incentive or tax result is guaranteed.']], related:['battery','utility'],
  questions:[['facility','Facility type','select',['Warehouse / industrial','Retail / office','Hospitality','Campus / institution','Agriculture','Other / help me determine']],['authority','Decision role / site control','select',['Owner / decision maker','Facility or operations team','Authorized advisor','Tenant','Help me determine this']],['installation','Installation area','select',['Rooftop','Carport','Ground mount','Help me determine this']],['usage','Usage or scale (optional)','text',null,'kWh/month, kW or unknown'],['sites','Number of sites (optional)','text',null,'One, a portfolio, or unknown']]
 },
 {
  id:'battery', path:'battery-storage', name:'Battery storage', short:'Start with what must keep working.', eyebrow:'For homes, businesses & projects', headline:'Store energy with\na purpose in mind.',
  intro:'Backup, energy shifting and operational planning are different jobs. Define the job first, then explore the storage, controls and project requirements it may need.',
  audience:'Homeowners, facility teams and infrastructure stakeholders evaluating battery energy storage systems (BESS).',
  cards:[['Purpose before product','Identify whether your priority is supporting critical loads, using stored solar, managing peaks or investigating an infrastructure opportunity.'],['Power & energy','kW and MW describe power: the rate of delivery. kWh and MWh describe stored energy. Both matter when evaluating loads and duration.'],['The complete system','Switchgear, protection, controls, utility rules, location and the electrical design affect how a battery can operate. A battery alone does not guarantee islanding.']],
  detailTitle:'A battery decision begins with an operating scenario.',
  paragraphs:['Describe the loads or process you want to support. For backup, distinguish essential circuits from the entire property and share a desired duration if you know it. For commercial use, explain the operational objective; tariff and load data can come later.','Existing solar can influence the options, but compatibility and operating strategy require assessment. Commissioning, safety requirements, permits, controls, service and maintenance should form part of any proposed solution. Supplier and project-specific terms need confirmation before a commitment.','If you have a specification, use the appropriate units. If you do not, leave the optional power and energy fields blank. “Unknown” is a useful starting point, and avoids false precision. A qualified technical review must establish an appropriate configuration.'],
  next:'Share the purpose, site type, existing solar status, any known critical loads and desired duration. Tell us the power and energy separately if known.',
  faq:[['What is the difference between kW and kWh?','kW is a rate of power; kWh is an amount of energy. The same distinction applies to MW and MWh at larger scale.'],['Does every battery provide backup?','No. Backup depends on equipment configuration, controls, electrical design and approvals. The intended behavior must be verified.'],['Can storage be considered on its own?','Yes. Existing solar is one of the initial questions; new solar is not a requirement for an inquiry.']], related:['residential','commercial','utility'],
  questions:[['purpose','Primary purpose','select',['Critical-load backup','Solar energy shifting','Peak-demand planning','Infrastructure storage','Help me determine this']],['existingSolar','Existing solar','select',['Yes','No','Planned','Unknown']],['criticalLoads','Critical loads (optional)','text',null,'What needs to keep working?'],['duration','Desired backup duration (optional)','text',null,'Hours or unknown'],['power','Power required (optional)','text',null,'Value with kW or MW'],['energy','Energy capacity (optional)','text',null,'Value with kWh or MWh']]
 },
 {
  id:'robotics', path:'robotics', name:'Commercial robotics', short:'Find the right robot for the work.', eyebrow:'Task first. Product second.', headline:'Give repetitive work\na smarter next step.',
  intro:'Cleaning. Grounds care. Delivery. Material movement. Start with the task your team repeats, then explore whether a commercial robot fits the site and workflow.',
  audience:'Facilities, hospitality, grounds, logistics and other operating teams investigating commercial robotics.',
  cards:[['Describe the real work','Tell us what happens today, the usable area or route, the obstacles and the operating windows. Model selection comes after the task.'],['See manufacturer evidence','Use official product material to understand a category. PUDU GT3 is a robotic mower; CC1 Pro is a commercial cleaning robot. Site suitability still needs review.'],['Review from where you are','Start virtually through a conversation, official footage, remote site information and supplier-supported technical review, subject to supplier availability.']],
  detailTitle:'A virtual path to a more useful robotics decision.',
  paragraphs:['For grounds care, a later review can address turf area, slope, obstacles, access, charging and storage. Sol does not have a GT demonstration unit and does not offer an in-person Sol GT demo. Remote information and supplier review guide the initial evaluation.','For cleaning, start with the surfaces, usable area, furniture, traffic and current process. For delivery and industrial transport, route dimensions, payload, transitions and interactions with people need evaluation. Do not assume a product can handle every surface or route shown in a general video.','Supervised inspection inquiries need a defined, permitted task and a human operating plan. No autonomous law-enforcement capability is offered. Availability, configuration, final price, warranty, commissioning, support and service territory must be confirmed with the relevant supplier.'],
  next:'Choose a task, share the location, describe the current workflow and timing. Operating detail can follow after the first conversation. No physical pilot is a prerequisite for starting.',
  faq:[['Can we begin without an on-site demonstration?','Yes. Begin virtually with the task, remote site information and official product material. Sol has no GT demo unit.'],['Which mower models and prices are available?','This preview references the verified official GT3 page. A supplier must confirm model availability, configuration, accessories, pricing and support for your site.'],['Will a robot replace every part of the job?','That depends on the workflow. Evaluate coverage, exceptions, human oversight, maintenance and total cost before a purchase decision.']], related:['commercial','battery'],
  questions:[['task','Primary robotics task','select',['Cleaning','Grounds care','Delivery / hospitality','Industrial transport','Supervised inspection','Help me determine this']],['workflow','Current workflow / immediate need','text',null,'What repeats, and what makes it difficult?'],['area','Usable area or route (optional)','text',null,'Approximate square feet, acres or route length'],['surfaces','Surface / setting (optional)','text',null,'Hard floors, carpet, turf, mixed, or unknown']]
 },
 {
  id:'utility', path:'utility-scale-solar', name:'Utility-scale solar', short:'Move from land to evidence.', eyebrow:'For land & energy stakeholders', headline:'Start with a site.\nBuild a case with evidence.',
  intro:'Organize an early solar or solar-plus-storage opportunity around site control, utility context, development stage and the information needed for the next decision.',
  audience:'Landowners, authorized brokers, developers and project stakeholders with a nonconfidential utility-scale opportunity.',
  cards:[['Land & role','Explain the location, approximate acreage and your relationship to the opportunity. Distinguish ownership, option, representation and early exploration.'],['Power & grid evidence','Grid proximity is a clue. Documented utility correspondence, studies and the applicable interconnection process carry different evidentiary weight.'],['Stage & next decision','An idea, a controlled site and a project with studies have different needs. Share the stage and what you want a next conversation to resolve.']],
  detailTitle:'An origination conversation that respects project reality.',
  paragraphs:['Early infrastructure decisions benefit from a clear account of what is known and what is still an assumption. Location, land area, access, development stage and utility territory help frame a first conversation. They do not establish buildability, capacity, permits or commercial viability.','Sol’s role is origination, qualification, business development and project coordination. Licensed engineering, EPC work, installation, utility approvals, financing and other delivery functions require appropriate counterparties and project-specific agreements. An inquiry is not an offer of capital or a development commitment.','Keep the initial description nonconfidential. Do not upload title files, confidential contracts, site security details or utility documents here. If deeper due diligence is appropriate, document-sharing terms and a secure channel should be agreed first.'],
  next:'Provide a general location, site role, approximate acres or MW if known, utility territory, project stage and timing. State clearly whether supporting utility evidence exists.',
  faq:[['Does a nearby substation mean capacity is available?','No. Physical proximity does not establish interconnection feasibility or available capacity. Utility evidence and the applicable studies are required.'],['Can I submit an opportunity before controlling the land?','Yes. State your actual role and stage accurately. Site control remains a separate qualification question.'],['Is Sol the engineering or EPC contractor?','Sol is the origination, qualification, business-development and coordination contact. Delivery scope and counterparties are established for each project.']], related:['battery','data-center'],
  questions:[['authority','Site control / your role','select',['Owner','Option / control agreement','Authorized representative','Developer / project team','Exploring / unknown']],['scale','Approximate acreage or MW (optional)','text',null,'Include acres or MW; unknown is fine'],['utility','Utility territory (optional)','text',null,'Utility name or unknown'],['stage','Project stage','select',['Early idea','Site identified','Site controlled','Studies / applications underway','Help me determine this']],['evidence','Utility evidence available?','select',['Utility correspondence','Formal study / agreement','Only proximity information','None yet','Unknown']]]
 },
 {
  id:'data-center', path:'data-center-infrastructure', name:'AI / data-center infrastructure', short:'Put power readiness before promises.', eyebrow:'For developers & infrastructure teams', headline:'Power. Site. Timing.\nStart with what is known.',
  intro:'Frame an AI or data-center infrastructure opportunity around the site, power requirement, desired delivery date and the evidence behind the plan.',
  audience:'Developers, landowners, authorized advisors and infrastructure stakeholders evaluating prospective data-center sites or power strategies.',
  cards:[['Define the requirement','Initial and ultimate power needs are different. State each in MW, if known, and distinguish a desired date from a utility-confirmed delivery date.'],['Check the basis','Utility correspondence, formal studies, site control and development status help separate an early prospect from a supported opportunity.'],['Coordinate the next review','Establish roles, information-sharing boundaries and the specialists needed to review power, land and technical constraints.']],
  detailTitle:'A serious infrastructure conversation starts with specific questions.',
  paragraphs:['A large parcel and nearby power lines do not make a shovel-ready data-center site. Early screening should distinguish observed facts, documented utility evidence and assumptions. Begin with nonconfidential information and the decision you are trying to make.','Sol acts as an origination, qualification, business-development and project-coordination contact. Sol is not offering cloud hosting, operating a data center, guaranteeing power delivery or representing unverified land as powered. Engineering, construction, financing and operating responsibilities are project-specific.','Fiber, cooling, electrical architecture, critical systems, site drawings and utility documents belong in a later secure due-diligence process. Solar and storage may form part of a strategy, but do not automatically satisfy a data center’s reliability, capacity or delivery-date requirements.'],
  next:'Share a general location, site-control position, initial and ultimate MW if known, desired power-delivery date, stage and availability of utility evidence.',
  faq:[['Can you confirm available power from a map?','No. Maps and proximity are screening inputs. Capacity, timing and interconnection require utility-supported evidence.'],['Do you provide cloud or colocation services?','No. This path is for prospective site, power and infrastructure opportunities.'],['Can solar or BESS be included?','Yes, as a potential part of a project-specific power strategy. Reliability and delivery requirements need appropriate technical review.']], related:['utility','battery'],
  questions:[['authority','Site control / your role','select',['Owner','Option / control agreement','Authorized representative','Developer / project team','Exploring / unknown']],['initialPower','Initial power (optional)','text',null,'MW or unknown'],['ultimatePower','Ultimate power (optional)','text',null,'MW or unknown'],['powerDate','Desired power-delivery date (optional)','text',null,'A target, not a utility commitment'],['stage','Project stage','select',['Early concept','Site search','Site identified / controlled','Utility review underway','Help me determine this']],['evidence','Utility evidence available?','select',['Utility correspondence','Formal study / agreement','Only proximity information','None yet','Unknown']]]
 }
];
export const consent = {
 version:'SOL-GH-2026-09-12-v1',
 request:'I ask Sol Solar Solutions LLC to respond about this specific inquiry using my selected response method.',
 marketing:'Optional: Email me future Sol Solar Solutions updates. I can opt out at any time. This is not required for a response.'
};
