// Customer-facing preview corrections. No collection or publication is enabled here.
export function improvePage(html, kind) {
  html = html.replaceAll('Find my project fit', 'Prepare project brief');
  html = html.replace('Design preview · inquiry preparation only', 'Website preview · online sending is not enabled');
  html = html.replaceAll('Compare directions', 'Design options');
  html = html.replaceAll('<a class="btn" href="/fit/">Prepare project brief</a>', '<a class="btn" href="/contact/">Contact Salvador</a>');
  if (kind === 'home') {
    html = html.replace('Power your<br>next move.', 'Solar. Storage.<br>Robotics.');
    html = html.replace('Solar, storage and robotics for your home, business or next big project. Start with the right questions. Move forward with a clearer plan.', 'Explore solar for your home or business, battery storage and commercial robots. For larger projects, start with utility-scale solar or AI/data-center infrastructure.');
    html = html.replace('<a class="btn" href="/fit/">Prepare project brief <span aria-hidden="true">↗</span></a><a class="text-link" href="#solutions">Explore solutions <span aria-hidden="true">↓</span></a>', '<a class="btn" href="#solutions">Choose a solution ↓</a><a class="btn btn-outline" href="tel:+19495915731">Call Salvador</a>');
    html = html.replace('No purchase commitment. Just a practical starting point.', 'Choose your project below, review what matters, then call Salvador or prepare a brief for your conversation. No purchase commitment.');
    html = html.replace('</p></div><div class="hero-art"', '</p><nav class="project-shortcuts" aria-label="Choose your project"><a href="/residential-solar/">Home solar →</a><a href="/commercial-solar/">Business solar →</a><a href="/battery-storage/">Battery storage →</a><a href="/robotics/">Commercial robots →</a><a href="/utility-scale-solar/">Utility solar →</a><a href="/data-center-infrastructure/">AI / data centers →</a></nav></div><div class="hero-art"');
    html = html.replace('Start your project conversation ↗', 'Prepare a brief before calling ↗');
  }
  if (kind === 'fit') {
    html = html.replace('Let’s find<br>the fit.', 'Prepare your<br>project brief.');
    html = html.replace('Begin with the goal. Share only what you know. “Unknown” is a useful answer.', 'Organize your project before speaking with Salvador. Choose a solution, add the project details, then copy or save your brief. “Unknown” is a useful answer.');
    html = html.replace('Preview: prepare a brief on this device. Nothing is submitted to Sol.', 'This guide does not send an inquiry. Your answers stay on this device. To contact Salvador now, call (949) 591-5731.');
    html = html.replace('How should we reach you?', 'Contact details for your brief');
    html = html.replace('<div class="hero-actions"><button type="button" class="btn" id="copy-brief">', '<p><a class="btn" href="tel:+19495915731">Call Salvador · (949) 591-5731</a></p><p class="fine">Have this brief ready for your call. Calling opens your phone app; it does not send the brief or book an appointment.</p><div class="hero-actions"><button type="button" class="btn" id="copy-brief">');
  }
  return html;
}

export const reviewGallery = `<main class="gallery" id="main"><span class="eyebrow">Owner review · design options</span><h1>Open the website.</h1><p>Start with Golden Hour. Each option opens as a normal, full-page website, with all six solution pages. These previews let visitors explore the services, prepare a project brief and open a phone call to Salvador.</p><div class="gallery-tiles"><article class="gallery-tile"><span class="eyebrow">Recommended</span><h2>Golden Hour</h2><p>Warm charcoal, ivory and gold. The recommended corporate direction.</p><a class="btn" href="/">Open Golden Hour →</a></article><article class="gallery-tile"><span class="eyebrow">Alternative</span><h2>Daybreak</h2><p>Cream and green, with a bright editorial layout.</p><a class="btn btn-outline" href="/daybreak/">Open Daybreak →</a></article><article class="gallery-tile"><span class="eyebrow">Alternative</span><h2>Command</h2><p>A structured slate layout for infrastructure conversations.</p><a class="btn btn-outline" href="/command/">Open Command →</a></article></div><section><h2>What works in this preview?</h2><ul><li>Open a solution page and read the project-specific guidance.</li><li>Use the three-step guide to prepare, copy or save a project brief.</li><li>Choose “Call Salvador” to open your phone app.</li></ul><p>Online inquiry delivery is not enabled. Preparing a brief does not send it to Sol. The existing production website remains unchanged.</p><a class="text-link" href="/contact/">Contact options →</a></section></main>`;

export const contactPage = `<main class="report" id="main"><span class="eyebrow">Sol Solar Solutions · Salvador Castillo</span><h1>Talk about your project.</h1><p>For solar, storage, commercial robotics or infrastructure opportunities, start with your location, your goal and your timing.</p><p><a class="btn" href="tel:+19495915731">Call (949) 591-5731</a></p><p class="fine">Opens your phone app. Availability and the next conversation are arranged directly; this page does not reserve an appointment.</p><h2>Prefer to organize the details first?</h2><p>The guided brief asks questions for your specific project, including the main contact’s own working hours, best calling time and local time zone. You can copy or save the result for your conversation.</p><a class="btn btn-outline" href="/fit/">Prepare project brief →</a><p>Online sending is not enabled in this preview. Your brief stays on your device; Sol does not receive it automatically.</p><a class="text-link" href="/#solutions">Explore the six solutions →</a></main>`;
